name: Install & test conda-forge package
on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install homonim from conda-forge
      run: |
        conda install -c conda-forge homonim
    - name: Test homonim CLI
      timeout-minutes: 5
      run: |
        pwd
        ls -R
        mkdir ./data/test_example/homogenised/
        homonim fuse --help
        homonim fuse -m gain-blk-offset -k 5 5 -od ./data/test_example/homogenised -ovw ./data/test_example/source/3324c_2015_1004_05_0182_RGB.tif  ./data/test_example/reference/LANDSAT-LC08-C02-T1_L2-LC08_171083_20150923_B432_Byte.tif
        ls ./data/test_example/homogenised/*
        test -f ./data/test_example/homogenised/3324c_2015_1004_05_0182_RGB_HOMO_cREF_mGAIN-BLK-OFFSET_k5_5.tif && echo "Test OK"
